name: pitm
version: 0.0.1
publish_to: none
description: A watcher client that makes you don't need to register a company to access payments. Support WeChat Pay, Alipay, PayPal.
environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  firebase_analytics: ^10.0.4
  firebase_core: ^2.1.1
  url_launcher: ^6.1.8
  flutter_local_notifications: ^13.0.0
  sentry_flutter: ^6.19.0
  permission_handler: ^10.2.0
  wakelock: ^0.6.2
  flutter_notification_listener: ^1.3.2
  fluttertoast: ^8.1.2
  flutter_screenutil: ^5.6.1
  unicons: ^2.1.0
  get: 4.6.5
  flutter:
    sdk: flutter
  device_apps: ^2.2.0
  cached_memory_image: ^1.3.1
  disable_battery_optimization: ^1.1.0+1
  syncfusion_flutter_xlsio: ^20.1.61-beta
  path_provider: ^2.0.12
  flutter_archive: ^5.0.0
  package_info_plus: ^3.0.3
  system_info2: ^3.0.1
  version: ^3.0.2
  ota_update:
    git:
      url: https://github.com/TechGeekD/ota_update.git
      ref: "master"
  flutter_markdown: ^0.6.14
  markdown: ^7.0.1
  realm: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
